### ISSUE TITLE
Опечатка в rus.hlf- мы её забыли исправить

### ISSUE THREAD

**Issue by VictorVG** [FarPlugins/UnInstall#4]
Там просто - дифф смержить:

--- ./src/UnInstall_Rus.hlf	Git 1e0eee398
+++ ./src/UnInstall_Rus.hlf_	workingcopy
@@ ---3,7 +++3,7 @@
 .Options CtrlStartPosChar=^<wrap>

```
 @Contents
---$^UnInstall ${PLUGIN_VERSION}#
+++$^#UnInstall ${PLUGIN_VERSION}#
 $^#Содержание#

  #Колонки#
```
- мы тэг решётки забыли, хотя в #3 эта мелочь была, но там ескайп её скрыл, а из-за неё в русском хелпе заголовок не красится.  В английском этой опечатки нет. Закоммитить чтоб опечатка под ногами не путалась.

**Comment by ctapmex** [comment]
спасибо

**Comment by VictorVG** [comment]
Ещё раз с Наступающим!
